parameters:
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    ups_access_key: '%env(UPS_ACCESS_KEY)%'
    ups_username: '%env(UPS_USERNAME)%'
    ups_password: '%env(UPS_PASSWORD)%'
    ups_account_number: '%env(UPS_ACCOUNT_NUMBER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Services\StripePayment:
        arguments:
            $stripeSecretKey: '%stripe_secret_key%'

    App\Services\UpsShipping:
        arguments:
            $accessKey: '%ups_access_key%'
            $username: '%ups_username%'
            $password: '%ups_password%'
            $accountNumber: '%ups_account_number%'